OrdererOrgs:
- Domain: orderernet
  Name: Orderer
  Specs:
  - SANS:
    - localhost
  - Hostname: orderer
PeerOrgs:
- Domain: sellernet
  Name: Seller
  Template:
    Count: 1
    SANS:
    - localhost
  Users:
    Count: 2
- Domain: transnet
  Name: Transporter
  Template:
    Count: 1
    SANS:
    - localhost
  Users:
    Count: 2
- Domain: buyernet
  Name: Buyer
  Template:
    Count: 1
    SANS:
    - localhost
  Users:
    Count: 2
